### ISSUE TITLE
Updates to _config.yml not excluding

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-website-jekyll#11]
Hey @philipbaileynar 
I've tired to use that exclude syntax (see lines 40-45) in the `_config.yml` to exclude files that are not finished. It doesn't seem to be excluding them in either my local server or on line live. Any thoughts for what I'm doing wrong? 

Cheers,
Joe

**Comment by MattReimer** [comment]
Jumping in here.

`_config.yml` is mostly meant for managing files that should never be published. I wouldn't use it for markdown files. 

It DOES works on my machine.... but that's probably because you need to shut down the bundle exec process and restart it in order to see the changes/

my suggestion would be a choice. either 

1. Use a branch. I know it's more git work but this is the right way to do it
2. exclude a whole folder and keep your drafts in there:

```
exclude:
  - src
  - LICENSE
  - README.md
  - _config.yml
  - package.json
  - yarn.lock
  - script
  - js
  - TEMPLATE
  - Gemfile*
  - _drafts
```
Then move them out of drafts when you're ready.

**Comment by joewheaton** [comment]
Big adventure for me... I will tiptoe into branch. Can I still make edits
and commits on master branch while leaving in progress stuff off on non
merged branch?
